---
title: "spunk::"
description: |
  Reproducible packaged analysis
site: 
  distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

library(tidyverse)
library(sperm)
library(targets)
library(gt)


```



```{r pkg, message=FALSE}
# packages used in this readme
library(tidyverse)
library(sperm)
library(targets)
library(gt)

```

This is the [packaged analysis](https://github.com/softloud/spunk) accompanying the Cochrane review:

> Nutritional interventions for male infertility: a systematic review and meta-analysis

References for all resources linked in this analysis are provided in a [zotero collection](https://www.zotero.org/groups/4437063/diet_and_infertility_citations). 

## Contributors

- Maintainer: Charles T. Gray
- Data extraction: Mohammed Zafar and Kerry Mills
 
